cls 

#The reason there is no `r or `n being inserted with the script because at the end of the blank line being
#generated by "" there is automaticall a carrage return(`r) and a linefeed (`n) placed at the end of the line.




$xlCSV = 6
$Excelfilename = "C:\Users\pmanca.SCERIS\Documents\book1.xlsx"
$CSVfilename = "C:\file.csv"
$Excel = New-Object -comobject Excel.Application
$Excel.Visible = $False
$Excel.displayalerts=$False
$Workbook = $Excel.Workbooks.Open($ExcelFileName)
$Workbook.SaveAs($CSVfilename,$xlCSV)
$Excel.Quit()


$found = $false

Get-Content $CSVfilename | 

foreach-object{
    $pattern = ".*a"
    $Blank = ""

    if($_ -match $pattern){
        if($found -eq $false){

            $found = $true
        }


    }else{
        $found = $false
     }
    if($found -eq $true){

    $_
    $Blank


    }
    
    if($found -ne $true){

    $_

    }


}|Set-Content "C:\file2.csv"

$xlXLSX = 51
#$Excelfilename = "C:\Users\pmanca.SCERIS\Documents\book1.xlsx"
$CSVfilename2 = "C:\file2.csv"
$Excel = New-Object -comobject Excel.Application
$Excel.Visible = $False
$Excel.displayalerts=$False
$Workbook = $Excel.Workbooks.Open($CSVFileName2)
$Workbook.SaveAs($Excelfilename,$xlXLSX)
$Excel.Quit()
